CREATE ALIAS IF NOT EXISTS FT_INIT FOR "org.h2.fulltext.FullText.init";

CALL FT_INIT();

CALL FT_CREATE_INDEX('PUBLIC', 'PASTES', 'TITLE,CONTENT');



CREATE ALIAS IF NOT EXISTS FTL_INIT FOR "org.h2.fulltext.FullTextLucene.init";

CALL FTL_INIT();

CALL FTL_CREATE_INDEX('PUBLIC', 'PASTES', 'TITLE,CONTENT');
